### PR TITLE
add screenshoot for studio

### PR DESCRIPTION
**Pull request by corinnekrych**
@danielpassos this PR is to add images needed in global.json from fh-templates-app for our next release. pls review and merge.

### CODE REVIEW

**Comment by corinnekrych** [comment]
@danielpassos closing this PR. After discussion with @jasonmadigan it seems to be a better approach to put images in fh-templates-apps

**Comment by danielpassos** [comment]
@corinnekrych Any special reason?

**Comment by corinnekrych** [comment]
@danielpassos here it is: https://github.com/feedhenry/fh-template-apps/blob/master/screenshots/apps/sync_app/android-sync.png

**Comment by corinnekrych** [comment]
@danielpassos it's better to put them in fh-templates to avoir templates app to be cluttered with non useful information. A screenshot is not needed to run a build of android sync.

**Pull request closed without merging**
