### PR TITLE
Rhmap 2530

### PR DESCRIPTION
**Pull request by secondsun**
I've added a LICENSE file, a README file, and added the License plugin to the project.

# How to Test
```
./gradlew licenseAndroidMain
```
Will check the license in the test of the *app* project directory.

Also verify the content of README.md and LICENSE.  I used the standard FH license info.

### CODE REVIEW

**Comment by secondsun** [comment]
@wei-lee @danielpassos :eyes: ?

**Comment by wei-lee** [comment]
:eyes:

**Comment by wei-lee** [comment]
looks good!

**Comment by secondsun** [comment]
Landed @https://github.com/feedhenry-templates/sync-android-app/commit/3496c31dfa753b777c69badddfa3ba6bffcc6f6e

**Pull request closed without merging**
