### PR TITLE
RHMAP-2594 Update sdk version

### PR DESCRIPTION
**Pull request by david-martin**

### CODE REVIEW

**Comment by secondsun** [comment]
-1 The sync fixes/support are not in 2.4.1

**Comment by david-martin** [comment]
@secondsun what version should it be?

**Comment by secondsun** [comment]
@david-martin Until we verify with gingerbread 3.0.0.  If this gets verified against Gingerbread it should be 2.5.0 because we added two public methods in the FHHttpClient class.

**Comment by danielpassos** [comment]
@david-martin I'm wonder why you are updating the fh-android-sdk version **before** we release it?

**Comment by wei-lee** [comment]
looks good

**Comment by danielpassos** [comment]
This PR broke the app, because the app is not looking for the release repo (only for the snapshot). I'm going to fix it direct on master.

**Pull request merged**
